import { test } from 'node:test';
import assert from 'node:assert/strict';
import { closeSync, mkdirSync, mkdtempSync, openSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';

// Exercise the actual inline workflow steps against throwaway repositories
// whose HEAD^1 plays main, as in GitHub's PR merge commit checkout.
const workflow = readFileSync(new URL('../workflows/version-guard.yml', import.meta.url), 'utf8')
  .replaceAll('\r\n', '\n');
const scripts = [];
let collecting = null;
for (const line of workflow.split('\n')) {
  if (collecting !== null && (line === '' || line.startsWith(' '.repeat(10)))) {
    collecting.push(line.slice(10));
    continue;
  }
  if (collecting !== null) {
    scripts.push(collecting.join('\n'));
    collecting = null;
  }
  if (line === '        run: |') {
    collecting = [];
  }
}
if (collecting !== null) {
  scripts.push(collecting.join('\n'));
}
if (scripts.length !== 3) {
  throw new Error(`expected three inline workflow scripts, found ${scripts.length}`);
}
const bash = process.platform === 'win32'
  ? join(process.env.ProgramFiles ?? 'C:\\Program Files', 'Git', 'bin', 'bash.exe')
  : 'bash';

const packageJson = (fields) => `${JSON.stringify(fields, null, 2)}\n`;
const mainFiles = {
  'Cargo.toml': '[package]\nname = "flashtrace"\nversion = "0.12.1"\nedition = "2021"\n\n[dependencies]\nregex = "1"\n',
  'Cargo.lock': [
    '# This file is automatically @generated by Cargo.',
    'version = 4',
    '',
    '[[package]]',
    'name = "aho-corasick"',
    'version = "1.1.3"',
    '',
    '[[package]]',
    'name = "flashtrace"',
    'version = "0.12.1"',
    'dependencies = [',
    ' "regex",',
    ']',
    '',
  ].join('\n'),
  'npm/flashtrace/package.json': packageJson({
    name: 'flashtrace',
    version: '0.0.0',
    optionalDependencies: {
      '@flashtrace/linux-x64': '0.0.0',
      '@flashtrace/win32-x64': '0.0.0',
    },
  }),
  'npm/@flashtrace/linux-x64/package.json': packageJson({ name: '@flashtrace/linux-x64', version: '0.0.0' }),
  'npm/@flashtrace/win32-x64/package.json': packageJson({ name: '@flashtrace/win32-x64', version: '0.0.0' }),
  'CITATION.cff': [
    'cff-version: 1.2.0',
    'title: flashtrace',
    'authors:',
    '  - name: Example Author',
    'version: "0.12.1"',
    'date-released: "2026-07-23"',
    '',
  ].join('\n'),
};

// Paths with forward slashes work for Git for Windows' bash and for node.
const temporaryDirectory = (prefix) => mkdtempSync(join(tmpdir(), prefix)).replaceAll('\\', '/');

function git(repository, ...args) {
  const result = spawnSync('git', args, { cwd: repository, encoding: 'utf8' });
  assert.ifError(result.error);
  assert.equal(result.status, 0, `git ${args.join(' ')}: ${result.stderr}`);
}

// Writes each file, or removes it when its content is null.
function applyFiles(repository, files) {
  for (const [path, content] of Object.entries(files)) {
    const target = join(repository, path);
    if (content === null) {
      rmSync(target, { force: true });
    } else {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, content);
    }
  }
}

// Commits main (the baseline with `main` applied on top), then the PR's
// changes, and runs the workflow steps in order like GitHub: each with
// `bash -e`, stopping at the first failing step.
function guard({ main = {}, pr = {}, commitPr = true } = {}) {
  const repository = temporaryDirectory('version-guard-repository-');
  const runnerTemp = temporaryDirectory('version-guard-runner-');
  const stepDirectory = temporaryDirectory('version-guard-steps-');
  try {
    git(repository, 'init', '--quiet');
    git(repository, 'config', 'user.name', 'Version Guard Test');
    git(repository, 'config', 'user.email', 'version-guard@example.com');
    git(repository, 'config', 'core.autocrlf', 'false');
    git(repository, 'config', 'commit.gpgsign', 'false');
    applyFiles(repository, { ...mainFiles, ...main });
    git(repository, 'add', '--all');
    git(repository, 'commit', '--quiet', '--allow-empty', '--message', 'main');
    if (commitPr) {
      applyFiles(repository, pr);
      git(repository, 'add', '--all');
      git(repository, 'commit', '--quiet', '--allow-empty', '--message', 'PR');
    }

    let output = '';
    let status = 0;
    for (const [index, script] of scripts.entries()) {
      const scriptPath = `${stepDirectory}/step-${index}.sh`;
      const logPath = `${stepDirectory}/step-${index}.log`;
      writeFileSync(scriptPath, script);
      // One descriptor for both streams keeps their interleaving.
      const log = openSync(logPath, 'w');
      let result;
      try {
        result = spawnSync(bash, ['--noprofile', '--norc', '-e', scriptPath], {
          cwd: repository,
          stdio: ['ignore', log, log],
          timeout: 20_000,
          env: { ...process.env, RUNNER_TEMP: runnerTemp },
        });
      } finally {
        closeSync(log);
      }
      assert.ifError(result.error);
      assert.equal(result.signal, null);
      output += readFileSync(logPath, 'utf8');
      status = result.status;
      if (status !== 0) {
        break;
      }
    }
    return { status, output };
  } finally {
    for (const directory of [repository, runnerTemp, stepDirectory]) {
      rmSync(directory, { recursive: true, force: true, maxRetries: 3 });
    }
  }
}

const annotations = (output) => output.split('\n').filter((line) => line.startsWith('::error'));

function assertPasses(result) {
  assert.equal(result.status, 0, result.output);
  assert.deepEqual(annotations(result.output), [], result.output);
}

function assertFails(result, file, message) {
  assert.equal(result.status, 1, result.output);
  assert.deepEqual(annotations(result.output), [`::error file=${file}::${message}`], result.output);
}

const changedVersion =
  'The version must not be changed in a PR. It is bumped automatically by the release workflow (release:* labels).';
const removed = (file) =>
  `${file} is release-owned and must not be removed in a PR; removing it must update this guard and the release workflow.`;

test('a PR that leaves the release-owned files alone passes every step', () => {
  const result = guard({ pr: { 'README.md': '# flashtrace\n' } });
  assertPasses(result);
  assert.match(result.output, /^Cargo\.toml base: 0\.12\.1, PR: 0\.12\.1$/m);
  assert.match(result.output, /^Cargo\.lock base: 0\.12\.1, PR: 0\.12\.1$/m);
  assert.match(result.output, /^npm\/@flashtrace\/win32-x64\/package\.json base: 0\.0\.0, PR: 0\.0\.0$/m);
  assert.match(result.output, /^PR   date-released: 2026-07-23$/m);
});

test('fails when HEAD^1 cannot be resolved', () => {
  const result = guard({ commitPr: false });
  assert.equal(result.status, 1, result.output);
  assert.deepEqual(annotations(result.output),
    ['::error::Cannot resolve HEAD^1; the guard needs fetch-depth: 2 on checkout.']);
});

const versionChanges = [
  ['Cargo.toml', mainFiles['Cargo.toml'].replace('version = "0.12.1"', 'version = "0.13.0"')],
  ['Cargo.lock', mainFiles['Cargo.lock'].replace('version = "0.12.1"', 'version = "0.13.0"')],
  ['npm/@flashtrace/linux-x64/package.json', packageJson({ name: '@flashtrace/linux-x64', version: '0.13.0' })],
];
for (const [file, content] of versionChanges) {
  test(`rejects a version change in ${file}`, () => {
    assertFails(guard({ pr: { [file]: content } }), file, changedVersion);
  });
}

test('rejects a version change in the main npm package even with matching pins', () => {
  const file = 'npm/flashtrace/package.json';
  const content = mainFiles[file].replaceAll('0.0.0', '0.13.0');
  assertFails(guard({ pr: { [file]: content } }), file, changedVersion);
});

test('only reads the flashtrace entry of Cargo.lock', () => {
  const content = mainFiles['Cargo.lock'].replace('version = "1.1.3"', 'version = "1.2.0"');
  assertPasses(guard({ pr: { 'Cargo.lock': content } }));
});

for (const file of ['Cargo.toml', 'Cargo.lock', 'npm/flashtrace/package.json', 'npm/@flashtrace/win32-x64/package.json']) {
  test(`rejects removing ${file}`, () => {
    assertFails(guard({ pr: { [file]: null } }), file, removed(file));
  });
}

test('rejects a guarded file that lost its version', () => {
  const content = mainFiles['Cargo.toml'].replace('version = "0.12.1"\n', '');
  assertFails(guard({ pr: { 'Cargo.toml': content } }), 'Cargo.toml',
    'No version found in Cargo.toml; the release workflow needs one to bump.');
});

// Transitional until the Rust CLI is on main; see the guard's comment.
test('skips a guarded file that main does not have yet', () => {
  const result = guard({ main: { 'Cargo.toml': null, 'Cargo.lock': null }, pr: { 'Cargo.toml': mainFiles['Cargo.toml'] } });
  assertPasses(result);
  assert.match(result.output, /^Cargo\.toml does not exist on the base branch; nothing to guard\.$/m);
  assert.match(result.output, /^Cargo\.lock does not exist on the base branch; nothing to guard\.$/m);
});

test('rejects a new platform package', () => {
  const file = 'npm/@flashtrace/darwin-arm64/package.json';
  const result = guard({ pr: { [file]: packageJson({ name: '@flashtrace/darwin-arm64', version: '0.0.0' }) } });
  assertFails(result, file,
    `${file} is a new platform package; adding one changes the release targets and must update this guard and the release workflow.`);
});

test('ignores files that are not platform package manifests', () => {
  assertPasses(guard({
    pr: {
      'npm/@flashtrace/linux-x64/README.md': '# linux-x64\n',
      'npm/@flashtrace/linux-x64/bin/package.json': packageJson({ version: '9.9.9' }),
    },
  }));
});

test('accepts a main without platform packages', () => {
  assertPasses(guard({
    main: {
      'npm/@flashtrace/linux-x64/package.json': null,
      'npm/@flashtrace/win32-x64/package.json': null,
      'npm/flashtrace/package.json': packageJson({ name: 'flashtrace', version: '0.0.0' }),
    },
  }));
});

test('rejects a platform-package pin that does not match the version', () => {
  const file = 'npm/flashtrace/package.json';
  const content = mainFiles[file].replace('"@flashtrace/win32-x64": "0.0.0"', '"@flashtrace/win32-x64": "0.13.0"');
  const result = guard({ pr: { [file]: content } });
  assert.equal(result.status, 1, result.output);
  assert.match(result.output, /^optionalDependencies pins 0\.13\.0 do not match version 0\.0\.0$/m);
  // The version step passed; the CITATION step never ran.
  assert.match(result.output, /^npm\/flashtrace\/package\.json base: 0\.0\.0, PR: 0\.0\.0$/m);
  assert.doesNotMatch(result.output, /^Base version:/m);
});

test('rejects a missing main npm package in the pin step', () => {
  const file = 'npm/flashtrace/package.json';
  const result = guard({ main: { [file]: null } });
  assertFails(result, file,
    'The main npm package is missing; its optionalDependencies pins are release-owned.');
  assert.match(result.output, /^npm\/flashtrace\/package\.json does not exist on the base branch; nothing to guard\.$/m);
});

for (const [key, from, to] of [['version', '0.12.1', '0.13.0'], ['date-released', '2026-07-23', '2026-10-10']]) {
  test(`rejects a change to the CITATION.cff ${key} field`, () => {
    const content = mainFiles['CITATION.cff'].replace(`${key}: "${from}"`, `${key}: "${to}"`);
    assertFails(guard({ pr: { 'CITATION.cff': content } }), 'CITATION.cff',
      `The "${key}" field must not be changed in a PR. It is set automatically by the release workflow (release:* labels).`);
  });

  test(`rejects a CITATION.cff without the ${key} field`, () => {
    const content = mainFiles['CITATION.cff'].replace(`${key}: "${from}"\n`, '');
    assertFails(guard({ pr: { 'CITATION.cff': content } }), 'CITATION.cff',
      `No "${key}" field found in CITATION.cff; the release workflow needs one to update.`);
  });
}

test('accepts requoted CITATION.cff fields and other citation edits', () => {
  const content = mainFiles['CITATION.cff']
    .replace('version: "0.12.1"', 'version: 0.12.1')
    .replace('date-released: "2026-07-23"', 'date-released: 2026-07-23')
    .replace('Example Author', 'Another Author');
  assertPasses(guard({ pr: { 'CITATION.cff': content } }));
});

test('rejects removing CITATION.cff', () => {
  assertFails(guard({ pr: { 'CITATION.cff': null } }), 'CITATION.cff', removed('CITATION.cff'));
});

test('rejects a CITATION.cff that main does not have', () => {
  assertFails(guard({ main: { 'CITATION.cff': null } }), 'CITATION.cff',
    'CITATION.cff does not exist on the base branch; its release fields cannot be guarded.');
});

test('stops at the first failing step', () => {
  const result = guard({
    pr: {
      'Cargo.toml': versionChanges[0][1],
      'CITATION.cff': mainFiles['CITATION.cff'].replace('0.12.1', '0.13.0'),
    },
  });
  assertFails(result, 'Cargo.toml', changedVersion);
  assert.doesNotMatch(result.output, /^Base version:/m);
});
