/**
 * Builds a self-contained flashtrace executable for the current platform
 * using Node's Single Executable Application (SEA) support.
 *
 * Steps:
 *   1. Bundle src/sea-entry.mjs to CommonJS (the only format SEA accepts),
 *      baking the package.json version in via an esbuild define.
 *   2. Generate the SEA preparation blob (node --experimental-sea-config).
 *   3. Copy the running node executable and inject the blob with postject.
 *   4. On macOS, re-sign the modified binary ad hoc.
 *
 * Output: dist-sea/flashtrace-v<version>-<platform>-<arch>[.exe]
 */

import { build } from 'esbuild';
import { inject } from 'postject';
import { copyFileSync, chmodSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

// The blob is generated by (and the node executable copied from) the node
// running this script, so that node's SEA support is what ends up shipping.
const [major] = process.versions.node.split('.').map(Number);
if (major < 20) {
  console.error(`error: building SEA binaries requires Node >= 20, found ${process.versions.node}`);
  process.exit(1);
}

const root = fileURLToPath(new URL('..', import.meta.url));
const outDir = path.join(root, 'dist-sea');
const bundle = path.join(outDir, 'flashtrace.cjs');
const blob = path.join(outDir, 'flashtrace.blob');

const { version } = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));
const binaryName = `flashtrace-v${version}-${process.platform}-${process.arch}${process.platform === 'win32' ? '.exe' : ''}`;
const binary = path.join(outDir, binaryName);

mkdirSync(outDir, { recursive: true });

await build({
  entryPoints: [path.join(root, 'src', 'sea-entry.mjs')],
  bundle: true,
  format: 'cjs',
  platform: 'node',
  outfile: bundle,
  define: { FLASHTRACE_VERSION: JSON.stringify(version) },
  logOverride: {
    // import.meta does not exist in a CJS SEA bundle; esbuild would silently
    // replace it with {}. Anything still reaching it must fail the build.
    'empty-import-meta': 'error',
  },
});

function run(cmd, args) {
  const res = spawnSync(cmd, args, { stdio: 'inherit' });
  if (res.status !== 0) {
    console.error(`error: ${cmd} ${args.join(' ')} exited with ${res.status ?? res.error}`);
    process.exit(1);
  }
}

const seaConfig = path.join(outDir, 'sea-config.json');
writeFileSync(
  seaConfig,
  JSON.stringify(
    {
      main: path.relative(root, bundle).replaceAll(path.sep, '/'),
      output: path.relative(root, blob).replaceAll(path.sep, '/'),
      disableExperimentalSEAWarning: true,
    },
    null,
    2,
  ) + '\n',
);
// Paths in the SEA config are resolved against the working directory.
process.chdir(root);
run(process.execPath, ['--experimental-sea-config', seaConfig]);

copyFileSync(process.execPath, binary);
chmodSync(binary, 0o755);

// Injection invalidates the macOS code signature; strip it first and ad-hoc
// re-sign afterwards (Windows keeps working with a broken Authenticode
// signature, and Linux binaries are unsigned).
if (process.platform === 'darwin') run('codesign', ['--remove-signature', binary]);

await inject(binary, 'NODE_SEA_BLOB', readFileSync(blob), {
  sentinelFuse: 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2',
  machoSegmentName: process.platform === 'darwin' ? 'NODE_SEA' : undefined,
});

if (process.platform === 'darwin') run('codesign', ['--sign', '-', binary]);

console.log(path.relative(root, binary));
